const arrBuy = [



/*
{ 
	id  			: '', 
	title 			: '',
	manufacturer 	: '', 
	mark 			: '',
	code 			: '',
	country 		: '',
	shop 			: '', 
	 

	trader 			: { shop: '', seller: '', site: '', other: '', },

	cat 			: '', 	// техника, шмотка, еда и пр.
	cost 			: { total: 0, price: 0, item: 1, unit: '', },
	item 			: 1,
	note 			: '',

	cat 			: {
	
		car: { 			// автомобиль
			parts: { 		// запчасти
				hood: 1, 		// под капотом
				salon: 1, 		// салон
				under: 1, 		// под машиной

				body: 1, 		// кузов
				engine: 1, 		// двигатель
				wheel: 1, 		// ходовая часть
				ignition: 1, 	// система зажигания
				cooling: 1, 	// система охлаждения
				fuel: 1, 		// система топливная
				electric: 1, 	// электрика
			},

			liquid: 1, 		// жидкости
			service: 1, 	// для обслуживания
		},
		tool: {  		// инструменты

		},
		home : {
			water: 1, 		// водоснабжение
			wc: 1, 			// туалет
			kitchen: 1, 	// кухня
		},

		pc: {],				// компьютер
		phone: {],			// телефон

		studio: {],			// студийное

	}


},
*/








{
	id 				: '2023_04_01_1201',
	title 			: 'Реле 21. Поворотники',
	manufacturer 	: 'Febi',
	mark 			: '11574',
	trader 			: { shop: 'kharkiv_bus_auto', site: 'https://busauto.kh.ua/ua/p1214881753-febi-11574-rele.html',  },
	cost 			: { total: 185, price: 185, item: 1, unit: 'шт', },
	note 			: '',
},
{
	id 				: '2023_03_30_1003',
	title 			: 'ГБО 4',
	manufacturer 	: '',
	mark 			: '',
	cost 			: { total: 9000, price: 9000, item: 1, unit: 'шт', },
	note 			: 'Ціна з установкою. Пробіг - 443000 км',
},
{
	id 				: '2023_03_30_1002',
	title 			: 'Форсунки',
	manufacturer 	: 'Valtek',
	mark 			: '',
	cost 			: { total: 0, price: 0, item: 4, unit: 'шт', },
	note 			: 'ГБО 4',
},
{
	id 				: '2023_03_30_1001',
	title 			: 'Редуктор',
	manufacturer 	: 'Tomasetto',
	mark 			: '',
	cost 			: { total: 0, price: 0, item: 1, unit: 'шт', },
	note 			: 'ГБО 4',
},
{
	id 				: '2022_12_28_0901',
	title 			: 'Шланг пожежний',
	manufacturer 	: '',
	mark 			: '',
	cost 			: { total: 900, price: 45, item: 20, unit: 'м', },
	note 			: 'Для насоса фекального',
},
{
	id 				: '2022_12_28_0900',
	title 			: 'Насос фекальний',
	manufacturer 	: 'Delta',
	mark 			: 'WQD',
	trader 			: { shop: 'kharkiv_aquaera_1', },
	cost 			: { total: 2500, price: 2500, item: 1, unit: 'шт', },
},
{
	id 				: '2022_12_11_0800',
	title 			: 'Акумулятор',
	manufacturer 	: 'Exide 64 A/h',
	mark 			: '',
	trader 			: { shop: 'kharkiv_losk_10_22', },
	cost 			: { total: 3200, price: 3200, item: 1, unit: 'шт', },
},
{
	id 				: '2022_12_03_1202',
	title 			: 'Тепловентилятор',
	manufacturer 	: 'Crownberg',
	mark 			: 'CB-7747',
	trader 			: { shop: '', site: 'https://prom.ua/ua/p1617063396-teploventilyator-obogrevatel-dujka.html?adjust_campaign=share&adjust_adgroup=android&adjust_creative=product&utm_campaign=share_button&utm_medium=referral_link&utm_source=b2c_app_android',  },
	cost 			: { total: 440, price: 440, item: 1, unit: 'шт', },
},
{
	id 				: '2022_12_03_1201',
	title 			: 'Тепловентилятор',
	manufacturer 	: 'Crownberg',
	mark 			: 'CB-7746',
	trader 			: { shop: '', site: 'https://prom.ua/ua/p1617063394-teploventilyator-obogrevatel-dujka.html?adjust_campaign=share&adjust_adgroup=android&adjust_creative=product&utm_campaign=share_button&utm_medium=referral_link&utm_source=b2c_app_android',  },
	cost 			: { total: 440, price: 440, item: 1, unit: 'шт', },
},
{
	id 				: '2022_12_03_1103',
	title 			: 'Омывайка для стекол 5 л',
	manufacturer 	: '',
	mark 			: '',
	trader 			: { shop: 'kharkiv_losk_2_4',  },
	cost 			: { total: 100, price: 20, item: 5, unit: 'л', },
},
{
	id 				: '2022_12_03_1102',
	title 			: 'Масло ГУР',
	manufacturer 	: 'Febi',
	mark 			: '№ 06161',
	trader 			: { shop: 'kharkiv_losk_2_4',  },
	cost 			: { total: 380, price: 380, item: 1, unit: 'л', },
	note 			: '320 или 380 грн',
},
{
	id 				: '2022_12_03_1101',
	title 			: 'Болт-пробка маслосливная ',
	manufacturer 	: '',
	mark 			: '',
	trader 			: { shop: 'kharkiv_losk_2_4',  },
	cost 			: { total: 50, price: 50, item: 1, unit: 'шт', },
},
{
	id 				: '2022_12_01_1705',
	title 			: 'SSD M.2 1TB',
	manufacturer 	: 'Kingston NV1',
	mark 			: '9KXJKEJ4RC6A66',
	trader 			: { shop: 'kharkiv_elmir_2', site: 'https://elmir.ua/ssd-drives/ssd-drive_m_2_1tb_kingston_nv1_snvs_1000g.html', },
	cost 			: { total: 2878, price: 2878, item: 1, unit: 'шт', },
},
{
	id 				: '2022_11_18_1304',
	title 			: 'Насос циркуляційний',
	manufacturer 	: 'Wilo',
	mark 			: 'Star-RS 25/6 (4032956)',
	trader 			: { shop: 'rozetka', site: 'https://rozetka.com.ua/wilo_star_rs_25_6_4032956/p5503491/characteristics/', },
	cost 			: { total: 3100, price: 3100, item: 1, unit: 'шт', },
},
{
	id 				: '2022_11_18_1303',
	title 			: 'Балаклава зимня',
	manufacturer 	: 'Флісова чорна',
	mark 			: '',
	trader 			: { shop: '', },
	cost 			: { total: 250, price: 250, item: 1, unit: 'шт', },
	note 			: 'на Ярославській',
},
{
	id 				: '2022_11_18_1302',
	title 			: 'Рукавиці',
	manufacturer 	: 'Флісові чорні',
	mark 			: '',
	trader 			: { shop: '', },
	cost 			: { total: 100, price: 100, item: 1, unit: 'шт', },
	note 			: 'на Ярославській',
},
{
	id 				: '2022_11_18_1301',
	title 			: 'Мішок спальний',
	manufacturer 	: '',
	mark 			: '',
	trader 			: { shop: '', },
	cost 			: { total: 1850, price: 1850, item: 1, unit: 'шт', },
	note 			: 'на Ярославській',
},
{
	id 				: '2022_10_28_1002',
	title 			: 'Олія моторна',
	manufacturer 	: 'Aral Blue Tronic',
	mark 			: '10w40, ACEA A3/B4, API SN, VW 501.01/505.00',
	trader 			: { shop: 'kharkiv_losk_2_4', },
	cost 			: { total: 0, price: 0, item: 4, unit: 'л', },
},
{
	id 				: '2022_10_28_1001',
	title 			: 'Олія моторна',
	manufacturer 	: 'Aral Blue Tronic',
	mark 			: '10w40, ACEA A3/B4, API SN, VW 501.01/505.00',
	trader 			: { shop: 'kharkiv_losk_2_4', },
	cost 			: { total: 0, price: 0, item: 1, unit: 'л', },
},
{
	id 				: '2022_10_28_1000',
	title 			: 'Фільтр масляний',
	manufacturer 	: 'Mahle',
	mark 			: 'OC 2640',
	trader 			: { shop: 'kharkiv_losk_2_4', },
	cost 			: { total: 0, price: 0, item: 1, unit: 'шт', },
	note 			: 'Made in Китай',
},
{ 
	id  			: '2022_10_29_1802',
	title 			: 'Вимикач фонарів заднього ходу', 
	manufacturer 	: 'Febi', 
	mark 			: '21760',
	cat 			: { },
	trader 			: { shop: 'kharkiv_losk_2_4', site: '', },
	cost 			: { total: 290, price: 290, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_10_29_1801',
	title 			: 'Фільтр повітряний (ДМРВ)', 
	manufacturer 	: 'Meyle', 
	mark 			: '1121290008',
	cat 			: { },
	trader 			: { shop: 'kharkiv_losk_2_4', site: '', },
	cost 			: { total: 220, price: 220, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_10_29_1800',
	title 			: 'Прокладка піддону картера двигуна', 
	manufacturer 	: 'Elring', 
	mark 			: '495.620',
	cat 			: { },
	trader 			: { shop: 'kharkiv_losk_2_4', site: '', },
	cost 			: { total: 640, price: 640, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_10_28_1300',
	title 			: 'Силикагель наполнитель для котов', 
	manufacturer 	: '', 
	mark 			: '',
	cat 			: { },
	trader 			: { shop: '', site: '', },
	cost 			: { total: 340, price: 340, item: 1, unit: 'шт', },
	note 			: '3.8 кг',
},
{ 
	id  			: '2022_10_28_1001',
	title 			: 'Прокладка дроссельной заслонки', 
	manufacturer 	: 'Elring', 
	mark 			: '',
	cat 			: { car: { parts: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', site: '', },
	cost 			: { total: 70, price: 70, item: 1, unit: 'шт', },
	note 			: '',
},
{ 
	id  			: '2022_10_28_1000',
	title 			: 'Спрей карб-клинер', 
	manufacturer 	: '', 
	mark 			: '',
	cat 			: { car: { }, },
	trader 			: { shop: 'kharkiv_losk_2_4', site: '', },
	cost 			: { total: 150, price: 150, item: 1, unit: 'шт', },
	note 			: '',
},
{ 
	id  			: '2022_09_05_1000',
	title 			: 'Шини 185/65/R14', 
	manufacturer 	: 'Goodyear', 
	mark 			: 'UltraGrip Ice 2',
	cat 			: { car: { parts: 1, }, },
	trader 			: { shop: 'kharkiv_shiny_diski_1', site: 'https://infoshina.com.ua/uk/goodyear-ultragrip-ice-2-185-65-r14-86t', },
	cost 			: { total: 8316, price: 2079, item: 4, unit: 'шт', },
	note 			: '185/65/R14 86T M+S',
},
{ 
	id  			: '2022_07_28_1803',
	title 			: 'Фільтр салону', 
	manufacturer 	: 'Shafer', 
	mark 			: 'SAK44',
	cat 			: { car: { parts: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 0, price: 0, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_07_28_1802',
	title 			: 'Патрубок радіатора грубки', 
	manufacturer 	: 'Meyle', 
	mark 			: '1198190014',
	cat 			: { car: { parts: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 0, price: 0, item: 1, unit: 'шт', },
	note 			: 'Короткий с гофрой, выход',
},
{ 
	id  			: '2022_07_28_1801',
	title 			: 'Патрубок радіатора грубки',
	manufacturer 	: 'JP Group', 
	mark 			: '1114304300',
	cat 			: { car: { parts: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 0, price: 0, item: 1, unit: 'шт', },
	note 			: 'Длинный, вход',
},
{ 
	id  			: '2022_07_28_1800',
	title 			: 'Радіатор грубки', 
	manufacturer 	: 'Febi', 
	mark 			: '',
	cat 			: { car: { parts: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 580, price: 600, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_29_0901',
	title 			: 'Коронка', 
	manufacturer 	: '32 мм', 
	mark 			: '',
	cat 			: { tool: 1, },
	trader 			: { shop: 'kharkiv_tc_barabashovo', },
	cost 			: { total: 2800, price: 2800, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_29_0900',
	title 			: 'Бак пластиковий', 
	manufacturer 	: 'Europlast', 
	mark 			: '300 л',
	cat 			: { home: { water: 1, }, },
	trader 			: { shop: 'kharkiv_tc_barabashovo', },
	cost 			: { total: 2800, price: 2800, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_05_0904',
	title 			: 'П\'ятерник', 
	manufacturer 	: '', 
	mark 			: '',
	cat 			: { home: { water: 1, }, },
	trader 			: { shop: 'kharkiv_aquaera_1', },
},
{ 
	id  			: '2022_06_05_0903',
	title 			: 'Манометр', 
	manufacturer 	: '', 
	mark 			: '',
	cat 			: { home: { water: 1, }, },
	trader 			: { shop: 'kharkiv_aquaera_1', },
},
{ 
	id  			: '2022_06_05_0902',
	title 			: 'Реле тиску', 
	manufacturer 	: 'Italtechnica', 
	mark 			: 'PM/5G',
	cat 			: { home: { water: 1, }, },
	trader 			: { shop: 'kharkiv_aquaera_1', },
},
{ 
	id  			: '2022_06_05_0901',
	title 			: 'Гідроакумулятор', 
	manufacturer 	: 'Euroaqua', 
	mark 			: '100 л',
	cat 			: { home: { water: 1, }, },
	trader 			: { shop: 'kharkiv_aquaera_1', },
	cost 			: { total: 6280, price: 6280, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_05_0900',
	title 			: 'Насос', 
	manufacturer 	: 'Euroaqua JET 100', 
	mark 			: '25117002-01',
	cat 			: { home: { water: 1, }, },
	trader 			: { shop: 'kharkiv_aquaera_1', },
	cost 			: { total: 3200, price: 3200, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_1112',
	title 			: 'Фільтр паливний', 
	manufacturer 	: 'Febi', 
	mark 			: '24073 8976',
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 220, price: 220, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_1111', 
	title 			: 'Свічки запалювання', 
	manufacturer 	: 'Denso', 
	mark 			: 'W20EPBR-S',
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 600, price: 150, item: 4, unit: 'шт', },
	note 			: 'Свечи зажигания трехлепестковые',
},
{ 
	id  			: '2022_06_09_1110',
	title 			: 'Олія трансмісійна', 
	manufacturer 	: 'Febi', 
	mark 			: '75W GL-4',
	cat 			: { car: { liquid: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 760, price: 380, item: 2, unit: 'л', },
},
{ 
	id  			: '2022_06_09_1109',
	title 			: 'Вода дистильована', 
	cat 			: { car: { liquid: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 50, price: 10, item: 5, unit: 'л', },
},
{ 
	id  			: '2022_06_09_1108',
	title 			: 'Антифриз',
	manufacturer 	: 'Hepu', 
	mark 			: 'P999-G12-005',
	country 		: 'deu',
	cat 			: { car: { liquid: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 750, price: 130, item: 5, unit: 'л', },
},
{ 
	id  			: '2022_06_09_1107',
	title 			: 'Патрубок картерних газів', 
	manufacturer 	: 'Topran', 
	mark 			: '109614 3800J49',
	vag 			: '037103211',
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 400, price: 400, item: 1, unit: 'шт', },
	note 			: 'Патрубок пластиковый Г-образный от клапана картерных газов',
},
{ 
	id  			: '2022_06_09_1106', 
	title 			: 'Фланець антифризу', 
	manufacturer 	: 'Febi', 
	mark 			: '12410 8624 PA66-GF30',
	vag 			: '037121145',
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 140, price: 140, item: 1, unit: 'шт', },
	note 			: 'На ГБЦ сбоку',
},
{ 
	id  			: '2022_06_09_1105', 
	title 			: 'Помпа', 
	manufacturer 	: 'INA', 
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 1000, price: 1000, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_1104', 
	title 			: 'Ролик', 
	manufacturer 	: 'INA', 
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 650, price: 650, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_1103', 
	title 			: 'Ролик ГРМ', 
	manufacturer 	: 'INA', 
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 500, price: 500, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_1102', 
	title 			: 'Ремінь клиновий', 
	manufacturer 	: 'Gates', 
	mark 			: '6389 MC',
	country 		: 'esp',
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 180, price: 180, item: 1, unit: 'шт', },
	note 			: 'Сначала был куплен INA с неровными зубьями за 260 грн, потом обменен на этот с ровными зубьями и дешевле гривен на 80',
},
{ 
	id  			: '2022_06_09_1101', 
	title 			: 'Ремінь полікліновий', 
	manufacturer 	: 'Contitech', 
	mark 			: '6 PK 1153',
	country 		: 'rou',
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 420, price: 420, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_1100', 
	title 			: 'Ремінь ГРМ', 
	manufacturer 	: 'Contitech', 
	mark 			: 'CT 630. 0433 10022022',
	country 		: 'deu',
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 530, price: 530, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_0831', 
	title 			: 'Резина листова. Рулончик', 
	trader 			: { shop: 'kharkiv_blagbaz', },
	cost 			: { total: 35, price: 35, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_0830', 
	title 			: 'Диск відрізний 32х300', 
	cat 			: { tool: { }, },
	trader 			: { shop: 'kharkiv_blagbaz', },
	cost 			: { total: 160, price: 80, item: 2, unit: 'шт', },
},
{ 
	id  			: '2022_06_07_1200', 
	title 			: 'Зарядний пристрій', 
	manufacturer 	: 'Dnipro-M', 
	mark 			: 'BC-16',
	site 			: 'https://dnipro-m.ua/tovar/zaryadnoe-ystroistvo-cb-16s/?tab=description',
	cat 			: { car: { }, },
	trader 			: { shop: 'merefa_dnipro_m', },
	cost 			: { total: 1800, price: 1800, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_07_1100', 
	title 			: 'Змішувач в ванну без носика (только душ)', 
	manufacturer 	: 'Haiba', 
	trader 			: { shop: 'merefa_rynok_santehnika_1', },
	cost 			: { total: 1100, price: 1100, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_20_1001', 
	title 			: 'Подсумок для 3 магазинов АК', 
	trader 			: { shop: 'kharkiv_armeysky_1', },
	cost 			: { total: 400, price: 400, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_20_1000', 
	title 			: 'Балаклава', 
	trader 			: { shop: 'kharkiv_gvardeysky_1', },
	cost 			: { total: 120, price: 120, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_20_0900', 
	title 			: 'Телефон', 
	manufacturer 	: 'Xiaomi', 
	mark 			: 'Poco M3 Pro 5G 4/64GB',
	site 			: 'https://elmir.ua/cell_phones/mobile_phone_xiaomi_poco_m3_pro_5g_4_64gb_black_eu.html',
	trader 			: { shop: 'kharkiv_elmir_2', },
	cost 			: { total: 7502, price: 7502, item: 1, unit: 'шт', },
	note 			: 'Вовке',
},
{ 
	id  			: '2022_05_17_1004', 
	title 			: 'Щітка по металу для болгарки', 
	site 			: 'https://dnipro-m.ua/tovar/shhetka-po-metallu-dnipro-m-konusnaya-gofr-provoloka-125mm/',
	trader 			: { shop: 'merefa_dnipro_m', },
	cost 			: { total: 80, price: 80, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_17_1003', 
	title 			: 'Свердла (набор)', 
	site 			: 'https://dnipro-m.ua/tovar/tovar-nabor-sverl-po-metalu/',
	trader 			: { shop: 'merefa_dnipro_m', },
	cost 			: { total: 230, price: 230, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_17_1002', 
	title 			: 'Диски для болгарки, 1 мм', 
	trader 			: { shop: 'merefa_dnipro_m', },
	cost 			: { total: 210, price: 21, item: 10, unit: 'шт', },
},
{ 
	id  			: '2022_05_17_1001', 
	title 			: 'Шуруповерт', 
	manufacturer 	: 'Dnipro-M', 
	mark 			: 'TD-32Q',
	site 			: 'https://dnipro-m.ua/tovar/drel-shurupovert-setevaya-td-32q/?tab=characteristics',
	trader 			: { shop: 'merefa_dnipro_m', },
	cost 			: { total: 1197, price: 1197, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_17_1000', 
	title 			: 'Болгарка', 
	manufacturer 	: 'Dnipro-M', 
	trader 			: { shop: 'merefa_dnipro_m', },
	cost 			: { total: 1700, price: 1700, item: 1, unit: 'шт', },
	note 			: '960 Вт. Нет на сайте',
},
{ 
	id  			: '2022_05_16_1001', 
	title 			: 'Каністра пластикова для бензину', 
	mark 			: '20 л',
	trader 			: { shop: 'kharkiv_avtograd', },
	cost 			: { total: 600, price: 600, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_16_1000', 
	title 			: 'Лійка пластикова для бензина', 
	trader 			: { shop: 'kharkiv_avtograd', },
	cost 			: { total: 100, price: 100, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_15_2200', 
	title 			: 'Power Bank', 
	manufacturer 	: 'No Name', 
	mark 			: '10000 mAh',
	trader 			: { other: 'Павлюченко И.', },
	cost 			: { total: 400, price: 400, item: 1, unit: 'шт', },
},
{
	id 				: '2022_05_04_1105',
	title 			: 'Ручка дверей',
	manufacturer 	: 'Topran',
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 320, price: 320, item: 1, unit: 'шт', },
	note 			: 'Задняя правая',
},
{
	id 				: '2022_05_04_1104',
	title 			: 'Ручка дверей',
	manufacturer 	: 'Topran',
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 320, price: 320, item: 1, unit: 'шт', },
	note 			: 'Задняя левая',
},
{
	id 				: '2022_05_04_1103',
	title 			: 'Ручка дверей',
	manufacturer 	: 'Topran',
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 500, price: 500, item: 1, unit: 'шт', },
	note 			: 'Водительская с замком-личинкой и проводом. Провод не нужен',
},
{
	id 				: '2022_05_04_1102',
	title 			: 'Рігеля',
	manufacturer 	: 'Febi',
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 160, price: 40, item: 4, unit: 'шт', },
	note 			: 'Упоры замков дверей. Шайбы тонкие, гнутся',
},
{
	id 				: '2022_05_04_1101',
	title 			: 'Кліпси дверних ручек',
	manufacturer 	: 'VAG',
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 200, price: 50, item: 4, unit: 'шт', },
	note 			: 'П-образные белые пластмасски',
},
{
	id 				: '2022_04_22_1003',
	title 			: 'Втулки стабілізатора',
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 150, price: 75, item: 2, unit: 'шт', },
	note 			: 'Резинки',
},
{
	id 				: '2022_04_22_1002',
	title 			: 'Гальмівні колодки',
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 900, price: 450, item: 2, unit: 'шт', },
	note 			: '2 комплекта = 8 штук, на все колеса',
},
{
	id 				: '2022_04_22_1001',
	title 			: 'Стойки-амортизаторы',
	manufacturer 	: 'Meyle',
	cat 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 3300, price: 1650, item: 2, unit: 'шт', },
	note 			: 'Передние - левая, правая',
},
{ 
	id  			: '2022_04_10_1000',
	title 			: 'Web-камера', 
	manufacturer 	: 'Media-Tech', 
	mark 			: 'LOOK V MT4107',
	cat 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_elmir_2', site: '', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_04_02_1000',
	title 			: 'Машинка для підстригання', 
	manufacturer 	: 'Philips', 
	mark 			: 'HC3510/15',
	cat 			: { home: {}, },
	trader 			: { shop: 'kharkiv_elmir_2', site: '', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
},
{
	id 				: '2021_12_09_1030',
	title 			: 'Компресор для колес',
	manufacturer 	: 'Winso',
	trader 			: { shop: 'kharkiv_losk_11_49', },
},
{
	id 				: '2021_12_09_1002',
	title 			: 'Масляний фільтр',
	trader 			: { shop: 'kharkiv_losk_9_97', },
},
{
	id 				: '2021_12_09_1001',
	title 			: 'Олія моторна',
	manufacturer 	: 'Valvoline MaxLife',
	mark 			: '10w40 Synthetic Technology',
	trader 			: { shop: 'kharkiv_losk_9_97', },
	cost 			: { total: 750, price: 130, item: 5, unit: 'л', },
	note 			: 'Бензин, газ, дизель. Допуск - VW 50200/50500',
},
{
	id 				: '2021_00_00_1206',
	title 			: 'ВВ Провода на свічки',
	manufacturer 	: 'Beru',
	mark 			: 'ZEF 561',
	country 		: 'fra',
	cat 			: { car: { part: 1, }, },
	trader 			: { seller: '_alexandr_sto_pivdennePushka', },
},
{
	id 				: '2021_00_000_1205',
	title 			: 'Кришка трамблера',
	manufacturer 	: 'Metzger',
},
{
	id 				: '2021_00_00_1204',
	title 			: 'Лямбда-зонд',
	manufacturer 	: 'Bosch',
	code 			: '0 258 005 133',
	country 		: 'fra',
	cat 			: { car: { part: 1, }, },
	trader 			: { seller: '_alexandr_sto_pivdennePushka', },
},
{
	id 				: '2021_00_00_1203',
	title 			: 'Патрубок ДМРВ-колектора',
	mark 			: 'хобот',
	trader 			: { shop: 'kharkiv_avtograd', },
	cost 			: { total: 500, price: 500, item: 1, unit: 'шт', },
	note 			: 'б/у',
},
{
	id 				: '2021_00_00_1202',
	title 			: 'ДМРВ',
	manufacturer 	: 'Bosch',
	trader 			: { shop: 'kharkiv_avtograd', },
	cost 			: { total: 2700, price: 2700, item: 1, unit: 'шт', },
	note 			: 'б/у',
},
{ 
	id  			: '2020_10_15_1000',
	title 			: 'Батарея ИПБ', 
	manufacturer 	: 'CSB 12В 9Ач', 
	mark 			: 'HR1234WF2',
	cat 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_elmir_2', },
	cost 			: { total: 1, price: 1, item: 2, unit: 'шт', },
},
{ 
	id  			: '2020_08_10_0900',
	title 			: 'Котушка запалювання', 
	manufacturer 	: 'Bremi', 
	mark 			: '',
	cat 			: { car: { parts: 1, }, },
	trader 			: { shop: 'kharkiv_losk_insideParts', },
	cost 			: { total: 900, price: 900, item: 1, unit: 'шт', },
},
{ 
	id  			: '2020_04_18_0900',
	title 			: 'Відеореєстратор', 
	manufacturer 	: 'Xiaomi Yi Smart', 
	mark 			: 'Dash Camera',
	cat 			: { car: { }, },
	trader 			: { shop: 'kharkiv_elmir_1', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
	note 			: 'Для Citroen C1, на ДР Скирда',
},
{ 
	id  			: '2019_11_19_1000',
	title 			: 'Ваги підлогові', 
	manufacturer 	: 'Mirta', 
	mark 			: 'SB-3120',
	cat 			: { home: {}, },
	trader 			: { shop: 'kharkiv_elmir_1', site: '', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
},
{ 
	id  			: '2018_06_04_1000',
	title 			: 'Ноутбук', 
	manufacturer 	: 'Lenovo', 
	mark 			: 'IdeaPad 320',
	cat 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_comfy_1', site: '', },
	cost 			: { total: 16000, price: 16000, item: 1, unit: 'шт', },
},
{ 
	id  			: '2018_03_12_1000',
	title 			: 'HDD SATA 2 Tb', 
	manufacturer 	: 'Seagate', 
	mark 			: 'Barracuda',
	cat 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_elmir_2', site: '', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
},
{ 
	id  			: '2018_01_23_1000',
	title 			: 'SSD SATA 128 Gb', 
	manufacturer 	: 'Silicon Power', 
	mark 			: 'A55',
	cat 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_elmir_1', site: '', },
	cost 			: { total: 1482, price: 1482, item: 1, unit: 'шт', },
},
{ 
	id  			: '2017_09_29_1000',
	title 			: 'USB Flash 64 Gb', 
	manufacturer 	: 'GoodRam', 
	mark 			: 'UTS3',
	cat 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_elmir_1', site: '', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
},
{ 
	id  			: '2008_06_16_1000',
	title 			: 'ИБП UPS', 
	manufacturer 	: 'Mustek', 
	mark 			: 'PowerMust 1400 USB',
	cat 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_elmir_1', site: '', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
},
{ 
	id  			: '2008_03_07_1600',
	title 			: 'Монітор TFT LCD', 
	manufacturer 	: 'LG Flatron', 
	mark 			: 'L204WT',
	cat 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_univermag_kharkiv', site: '', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
},
{ 
	id  			: '2007_11_21_1500',
	title 			: 'Сінтезатор', 
	manufacturer 	: 'Casio', 
	mark 			: 'CDP 100',
	cat 			: { studio: {}, },
	trader 			: { shop: 'kharkiv_atlanta_show', site: '', },
	cost 			: { total: 3510, price: 3510, item: 1, unit: 'шт', },
},














];



let objBuy = {};
arrBuy.forEach( k => {
	objBuy[ k.id ] = k;
});





