const arrListBuy = [



/*
{ 
	id  			: '', 
	title 			: '',
	hash 			: {},
	manufacturer 	: '', 
	mark 			: '',
	code 			: '',
	country 		: '',
	shop 			: '', 
	 

	trader 			: { shop: '', seller: '', site: '', other: '', },

	hash 			: {}, 	// техника, шмотка, еда и пр.
	cost 			: { total: 0, price: 0, item: 1, unit: '', },
	item 			: 1,
	note 			: '',

	hash 			: {
	
		car: { 			// автомобиль
			parts: { 		// запчасти
				hood: 1, 		// под капотом
				salon: 1, 		// салон
				under: 1, 		// под машиной

				body: 1, 		// кузов
				engine: 1, 		// двигатель
				wheel: 1, 		// ходовая часть
				ignition: 1, 	// система зажигания
				cooling: 1, 	// система охлаждения
				fuel: 1, 		// система топливная
				electric: 1, 	// электрика
			},

			liquid: 1, 		// жидкости
			service: 1, 	// для обслуживания
		},
		tool: {  		// инструменты

		},
		home : {
			water: 1, 		// водоснабжение
			wc: 1, 			// туалет
			kitchen: 1, 	// кухня
		},

		pc: {],				// компьютер
		phone: {],			// телефон

		studio: {],			// студийное

	}


},

hash: 

car: 1, 		// автомобіль
electro: 1, 	// електрика, електроніка
chemical: 1, 	// хімія

household: 1, 	// домашнее хозяйство, сад, огород, двор


*/






{
	id 				: '2023_09_21_1302',
	title 			: 'Подушка двигуна ',
	hash 			: { car: 1, },	
	manufacturer 	: 'Corteco',
	mark 			: '21652428',
	trader 			: { shop: 'kharkiv_losk_2_4', }, 
	cost 			: { total: 700, price: 700, item: 1, unit: 'шт', },
},
{
	id 				: '2023_09_21_1301',
	title 			: 'Подушка двигуна передня',
	hash 			: { car: 1, },	
	manufacturer 	: 'Corteco',
	mark 			: '21651935',
	trader 			: { shop: 'kharkiv_losk_2_4', }, 
	cost 			: { total: 1200, price: 1200, item: 1, unit: 'шт', },
},
{
	id 				: '2023_09_21_1300',
	title 			: 'Подушка двигуна задня',
	hash 			: { car: 1, },	
	manufacturer 	: 'Birth',
	mark 			: '5483',
	trader 			: { shop: 'kharkiv_losk_2_4', }, 
	cost 			: { total: 900, price: 900, item: 1, unit: 'шт', },
},
{
	id 				: '2023_09_17_1000',
	title 			: 'Реле 4-контактне 40 А',
	hash 			: { car: 1, },	
	manufacturer 	: 'Bosdq',
	mark 			: '',
	trader 			: { shop: 'kharkiv_losk_1_auto_elektryka', }, 	// змінити ID  в `db/list/list.store.js`
	cost 			: { total: 150, price: 30, item: 5, unit: 'шт', },
},
{
	id 				: '2023_09_05_1500',
	title 			: 'Реле 4-контактне, 30 А',
	hash 			: { car: 1, },	
	manufacturer 	: 'Bosch',
	mark 			: '0986AH0453',
	trader 			: { site: 'https://your-car.com.ua/product/0986ah0453/bosch/',  },
	cost 			: { total: 256, price: 64, item: 4, unit: 'шт', },
},
{
	id 				: '2023_09_01_0900',
	title 			: 'Реле 4-контактне',
	hash 			: { car: 1, },	
	manufacturer 	: 'Startvolt', 	// Русня
	mark 			: '',
	trader 			: { shop: 'kharkiv_avtograd', },
	cost 			: { total: 80, price: 80, item: 1, unit: 'шт', },
},
{
	id 				: '2023_08_17_1400',
	title 			: 'Лампи діодні для стоп-сигналів',
	hash 			: { car: 1, },
	manufacturer 	: '',
	mark 			: '',
	trader 			: { shop: 'kharkiv_losk', },
	cost 			: { total: 140, price: 70, item: 2, unit: 'шт', },
},
{
	id 				: '2023_08_17_1201',
	title 			: 'Кільця-ущільнювачі гумові для форсунок',
	hash 			: { car: 1, },
	manufacturer 	: 'Topran',
	mark 			: '101562',
	trader 			: { shop: 'kharkiv_losk_2_4', },
	cost 			: { total: 400, price: 100, item: 4, unit: 'шт', },
},
{
	id 				: '2023_08_17_1200',
	title 			: 'Прокладка впускного колектора',
	hash 			: { car: 1, },
	manufacturer 	: 'Viktor Reinz',
	mark 			: '71-29173-00',
	trader 			: { shop: 'kharkiv_losk_2_4', },
	cost 			: { total: 200, price: 200, item: 1, unit: 'шт', },
},
{
	id 				: '2023_08_14_1800',
	title 			: 'Лампи для передніх фар',
	hash 			: { car: 1, },
	manufacturer 	: '',
	mark 			: '',
	trader 			: { shop: '', },
	cost 			: { total: 150, price: 75, item: 2, unit: 'шт', },
},
{
	id 				: '2023_08_04_1500',
	title 			: 'Крісло офісне',
	hash 			: { home: 1, furniture: 1, },
	manufacturer 	: 'Новий стиль',
	mark 			: 'BOSS KD TILT PL64 (CH) ECO-30',
	trader 			: { shop: 'kharkiv_epicentr_1', },
	cost 			: { total: 3650, price: 3650, item: 1, unit: 'шт', },
},
{
	id 				: '2023_07_26_2100',
	title 			: 'Глушник задній',
	hash 			: { car: 1, },
	manufacturer 	: '',
	mark 			: '',
	trader 			: { shop: 'kharkiv_losk_2_4', },
	cost 			: { total: 2000, price: 2000, item: 1, unit: 'шт', },
},
{
	id 				: '2023_06_02_1833',
	title 			: 'Гідрокомпенсатори F-46516.30.TSTH',
	hash 			: { car: 1, },
	manufacturer 	: 'INA',
	mark 			: '420004010',
	trader 			: { site: '',  },
	cost 			: { total: 1512, price: 189, item: 8, unit: 'шт', },
	//note 			: 'Дмитрієв Євген Євгенович',
},
{
	id 				: '2023_06_02_1832',
	title 			: 'Сальник вала // ASW F WD FPAC 32x74x10',
	hash 			: { car: 1, },
	manufacturer 	: 'Elring',
	mark 			: '325.155',
	trader 			: { site: '',  },
	cost 			: { total: 90, price: 90, item: 1, unit: 'шт', },
	//note 			: 'Дмитрієв Євген Євгенович',
},
{
	id 				: '2023_06_02_1831',
	title 			: 'Прокладка клапанної кришки двигуна',
	hash 			: { car: 1, },
	manufacturer 	: 'Elring',
	mark 			: '915.653',
	trader 			: { site: '',  },
	cost 			: { total: 335, price: 335, item: 1, unit: 'шт', },
	//note 			: 'Дмитрієв Євген Євгенович',
},
{
	id 				: '2023_06_01_1001',
	title 			: 'Троси ручника',
	hash 			: { car: 1, },
	manufacturer 	: 'JP Group',
	mark 			: '1170303700',
	trader 			: { site: '',  },
	cost 			: { total: 700, price: 350, item: 2, unit: 'шт', },
},
{
	id 				: '2023_05_18_1321',
	title 			: 'Шумоізоляція',
	hash 			: { car: 1, },
	manufacturer 	: 'MultiMat PRO',
	mark 			: '',
	trader 			: { site: '',  },
	cost 			: { total: 1280, price: 270, item: 4, unit: 'шт', },
},
{
	id 				: '2023_05_18_1320',
	title 			: 'Віброізоляція',
	hash 			: { car: 1, },
	manufacturer 	: 'Vibrex',
	mark 			: '',
	trader 			: { site: '',  },
	cost 			: { total: 720, price: 180, item: 4, unit: 'шт', },
	note 			: '',
},
{
	id 				: '2023_05_18_1303',
	title 			: 'Олія моторна',
	hash 			: { car: 1, },
	manufacturer 	: 'Aral',
	mark 			: '',
	trader 			: { site: '',  },
	cost 			: { total: 1000, price: 1000, item: 4, unit: 'л', },
	note 			: '1 каністра, 4 л',
},
{
	id 				: '2023_05_18_1302',
	title 			: 'Фільтр олійний',
	hash 			: { car: 1, },
	manufacturer 	: 'Meyle',
	mark 			: '',
	trader 			: { site: '',  },
	cost 			: { total: 200, price: 200, item: 1, unit: 'шт', },
	note 			: '',
},
{
	id 				: '2023_05_18_1301',
	title 			: 'Склоочисники',
	hash 			: { car: 1, },
	manufacturer 	: 'Bosch',
	mark 			: '',
	trader 			: { site: '',  },
	cost 			: { total: 300, price: 300, item: 2, unit: 'шт', },
	note 			: 'за пару',
},
{
	id 				: '2023_05_17_1001',
	title 			: 'Скло лобове',
	hash 			: { car: 1, },
	manufacturer 	: '',
	mark 			: '',
	trader 			: { site: '',  },
	cost 			: { total: 2650, price: 2650, item: 1, unit: 'шт', },
	note 			: 'АР Сервіс',
},
{
	id 				: '2023_05_09_1001',
	title 			: 'Реле 67. Бензонасос',
	hash 			: { car: 1, },
	manufacturer 	: '',
	mark 			: '',
	trader 			: { site: '',  },
	cost 			: { total: 270, price: 270, item: 1, unit: 'шт', },
	note 			: '',
},
{
	id 				: '2023_05_08_1201',
	title 			: 'Лампи діодні',
	hash 			: { car: 1, },
	manufacturer 	: '',
	mark 			: '',
	trader 			: { site: '',  },
	cost 			: { total: 480, price: 120, item: 4, unit: 'шт', },
	note 			: '',
},
{
	id 				: '2023_05_06_1200',
	title 			: 'Колонка Bluetooth',
	hash 			: { electro: 1, },
	manufacturer 	: 'JBL',
	mark 			: 'Xtreme Big',
	trader 			: { site: 'https://kharkov.prom.ua/ua/p795971389-kolonka-xtreme-big.html?adjust_campaign=share&adjust_adgroup=android&adjust_creative=product&utm_campaign=share_button&utm_medium=referral_link&utm_source=b2c_app_android', },
	cost 			: { total: 665, price: 665, item: 1, unit: 'шт', },
},
{
	id 				: '2023_05_02_1000',
	title 			: 'Діагностичний адаптер VCDS VAG 22.3 ',
	hash 			: { car: 1, },
	manufacturer 	: 'VAG COM 22.3',
	mark 			: '',
	trader 			: { site: 'https://kharkov.prom.ua/ua/p1700609345-diagnosticheskij-adapter-vcds.html?adjust_campaign=share&adjust_adgroup=android&adjust_creative=product&utm_campaign=share_button&utm_medium=referral_link&utm_source=b2c_app_android', },
	cost 			: { total: 840, price: 840, item: 1, unit: 'шт', },
},
{
	id 				: '2023_04_28_1400',
	title 			: 'Очисник контактів',
	hash 			: { car: 1, chemical: 1, electro: 1, },
	manufacturer 	: 'Xado',
	mark 			: 'Verylube',
	trader 			: { site: 'https://xado.com/avtomobilnaya-himiya/ochistiteli-razlichnih-sistem-avtomobilya/ochistitel-kontaktov-s-effektom-udaleniya-vlagi', },
	cost 			: { total: 135, price: 135, item: 1, unit: 'шт', },
},
{
	id 				: '2023_04_18_1300',
	title 			: 'Шабельна пила',
	hash 			: { household: 1, },
	manufacturer 	: 'Dnipro-M',
	mark 			: '',
	trader 			: { shop: 'merefa_dnipro_m', site: 'https://dnipro-m.ua/tovar/sabelnaya-pila-sr-115/?campaignid=17136142487&adgroupid=&targetid=&adid=&network=x&keyword=&gclid=Cj0KCQjwmZejBhC_ARIsAGhCqndlkLZBzSjCdMK964s0F5KjB4-EOGnQ0x23b-p8lpWIP8BtgwqtRI4aAtWdEALw_wcB',  },
	cost 			: { total: 3800, price: 3800, item: 1, unit: 'шт', },
	note 			: '',
},
{
	id 				: '2023_04_18_1200',
	title 			: 'Розподільник запалювання',
	hash 			: { car: 1, },
	manufacturer 	: 'JP Group',
	mark 			: '1191100500',
	trader 			: { site: '',  },
	cost 			: { total: 1200, price: 1200, item: 1, unit: 'шт', },
	note 			: '',
},
{
	id 				: '2023_04_01_1201',
	title 			: 'Реле 21. Поворотники',
	hash 			: { car: 1, },
	manufacturer 	: 'Febi',
	mark 			: '11574',
	trader 			: { shop: 'kharkiv_bus_auto', site: 'https://busauto.kh.ua/ua/p1214881753-febi-11574-rele.html',  },
	cost 			: { total: 185, price: 185, item: 1, unit: 'шт', },
	note 			: '',
},
{
	id 				: '2023_03_30_1003',
	title 			: 'ГБО 4',
	hash 			: { car: 1, },
	manufacturer 	: '',
	mark 			: '',
	cost 			: { total: 9000, price: 9000, item: 1, unit: 'шт', },
	note 			: 'Ціна з установкою. Пробіг - 443000 км',
},
{
	id 				: '2023_03_30_1002',
	title 			: 'Форсунки',
	hash 			: { car: 1, },
	manufacturer 	: 'Valtek',
	mark 			: '',
	cost 			: { total: 0, price: 0, item: 4, unit: 'шт', },
	note 			: 'ГБО 4',
},
{
	id 				: '2023_03_30_1001',
	title 			: 'Редуктор',
	hash 			: { car: 1, },
	manufacturer 	: 'Tomasetto',
	mark 			: '',
	cost 			: { total: 0, price: 0, item: 1, unit: 'шт', },
	note 			: 'ГБО 4',
},
{
	id 				: '2022_12_28_0901',
	title 			: 'Шланг пожежний',
	hash 			: { household: 1, },
	manufacturer 	: '',
	mark 			: '',
	cost 			: { total: 900, price: 45, item: 20, unit: 'м', },
	note 			: 'Для насоса фекального',
},
{
	id 				: '2022_12_28_0900',
	title 			: 'Насос фекальний',
	hash 			: { household: 1, },
	manufacturer 	: 'Delta',
	mark 			: 'WQD',
	trader 			: { shop: 'kharkiv_aquaera_1', },
	cost 			: { total: 2500, price: 2500, item: 1, unit: 'шт', },
},
{
	id 				: '2022_12_11_0800',
	title 			: 'Акумулятор',
	hash 			: { car: 1, },
	manufacturer 	: 'Exide 64 A/h',
	mark 			: '',
	trader 			: { shop: 'kharkiv_losk_10_22', },
	cost 			: { total: 3200, price: 3200, item: 1, unit: 'шт', },
},
{
	id 				: '2022_12_03_1202',
	title 			: 'Тепловентилятор',
	hash 			: {},
	manufacturer 	: 'Crownberg',
	mark 			: 'CB-7747',
	trader 			: { shop: '', site: 'https://prom.ua/ua/p1617063396-teploventilyator-obogrevatel-dujka.html?adjust_campaign=share&adjust_adgroup=android&adjust_creative=product&utm_campaign=share_button&utm_medium=referral_link&utm_source=b2c_app_android',  },
	cost 			: { total: 440, price: 440, item: 1, unit: 'шт', },
},
{
	id 				: '2022_12_03_1201',
	title 			: 'Тепловентилятор',
	hash 			: {},
	manufacturer 	: 'Crownberg',
	mark 			: 'CB-7746',
	trader 			: { shop: '', site: 'https://prom.ua/ua/p1617063394-teploventilyator-obogrevatel-dujka.html?adjust_campaign=share&adjust_adgroup=android&adjust_creative=product&utm_campaign=share_button&utm_medium=referral_link&utm_source=b2c_app_android',  },
	cost 			: { total: 440, price: 440, item: 1, unit: 'шт', },
},
{
	id 				: '2022_12_03_1103',
	title 			: 'Омывайка для стекол 5 л',
	hash 			: { car: 1, },
	manufacturer 	: '',
	mark 			: '',
	trader 			: { shop: 'kharkiv_losk_2_4',  },
	cost 			: { total: 100, price: 20, item: 5, unit: 'л', },
},
{
	id 				: '2022_12_03_1102',
	title 			: 'Масло ГУР',
	hash 			: { car: 1, },
	manufacturer 	: 'Febi',
	mark 			: '№ 06161',
	trader 			: { shop: 'kharkiv_losk_2_4',  },
	cost 			: { total: 380, price: 380, item: 1, unit: 'л', },
	note 			: '320 или 380 грн',
},
{
	id 				: '2022_12_03_1101',
	title 			: 'Болт-пробка олієзливна',
	hash 			: { car: 1, },
	manufacturer 	: '',
	mark 			: '',
	trader 			: { shop: 'kharkiv_losk_2_4',  },
	cost 			: { total: 50, price: 50, item: 1, unit: 'шт', },
},
{
	id 				: '2022_12_01_1705',
	title 			: 'SSD M.2 1TB',
	hash 			: {},
	manufacturer 	: 'Kingston NV1',
	mark 			: '9KXJKEJ4RC6A66',
	trader 			: { shop: 'kharkiv_elmir_2', site: 'https://elmir.ua/ssd-drives/ssd-drive_m_2_1tb_kingston_nv1_snvs_1000g.html', },
	cost 			: { total: 2878, price: 2878, item: 1, unit: 'шт', },
},
{
	id 				: '2022_11_18_1304',
	title 			: 'Насос циркуляційний',
	hash 			: {},
	manufacturer 	: 'Wilo',
	mark 			: 'Star-RS 25/6 (4032956)',
	trader 			: { shop: 'rozetka', site: 'https://rozetka.com.ua/wilo_star_rs_25_6_4032956/p5503491/characteristics/', },
	cost 			: { total: 3100, price: 3100, item: 1, unit: 'шт', },
},
{
	id 				: '2022_11_18_1303',
	title 			: 'Балаклава зимня',
	hash 			: {},
	manufacturer 	: 'Флісова чорна',
	mark 			: '',
	trader 			: { shop: '', },
	cost 			: { total: 250, price: 250, item: 1, unit: 'шт', },
	note 			: 'на Ярославській',
},
{
	id 				: '2022_11_18_1302',
	title 			: 'Рукавиці',
	hash 			: {},
	manufacturer 	: 'Флісові чорні',
	mark 			: '',
	trader 			: { shop: '', },
	cost 			: { total: 100, price: 100, item: 1, unit: 'шт', },
	note 			: 'на Ярославській',
},
{
	id 				: '2022_11_18_1301',
	title 			: 'Мішок спальний',
	hash 			: {},
	manufacturer 	: '',
	mark 			: '',
	trader 			: { shop: '', },
	cost 			: { total: 1850, price: 1850, item: 1, unit: 'шт', },
	note 			: 'на Ярославській',
},
{
	id 				: '2022_10_28_1002',
	title 			: 'Олія моторна',
	hash 			: { car: 1, },
	manufacturer 	: 'Aral Blue Tronic',
	mark 			: '10w40, ACEA A3/B4, API SN, VW 501.01/505.00',
	trader 			: { shop: 'kharkiv_losk_2_4', },
	cost 			: { total: 0, price: 0, item: 4, unit: 'л', },
},
{
	id 				: '2022_10_28_1001',
	title 			: 'Олія моторна',
	hash 			: { car: 1, },
	manufacturer 	: 'Aral Blue Tronic',
	mark 			: '10w40, ACEA A3/B4, API SN, VW 501.01/505.00',
	trader 			: { shop: 'kharkiv_losk_2_4', },
	cost 			: { total: 0, price: 0, item: 1, unit: 'л', },
},
{
	id 				: '2022_10_28_1000',
	title 			: 'Фільтр масляний',
	hash 			: { car: 1, },
	manufacturer 	: 'Mahle',
	mark 			: 'OC 2640',
	trader 			: { shop: 'kharkiv_losk_2_4', },
	cost 			: { total: 0, price: 0, item: 1, unit: 'шт', },
	note 			: 'Made in Китай',
},
{ 
	id  			: '2022_10_29_1802',
	title 			: 'Вимикач фонарів заднього ходу', 
	hash 			: { car: 1, },
	manufacturer 	: 'Febi', 
	mark 			: '21760',
	hash 			: { },
	trader 			: { shop: 'kharkiv_losk_2_4', site: '', },
	cost 			: { total: 290, price: 290, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_10_29_1801',
	title 			: 'Фільтр повітряний (ДМРВ)', 
	hash 			: { car: 1, },
	manufacturer 	: 'Meyle', 
	mark 			: '1121290008',
	hash 			: { },
	trader 			: { shop: 'kharkiv_losk_2_4', site: '', },
	cost 			: { total: 220, price: 220, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_10_29_1800',
	title 			: 'Прокладка піддону картера двигуна', 
	hash 			: { car: 1, },
	manufacturer 	: 'Elring', 
	mark 			: '495.620',
	hash 			: { },
	trader 			: { shop: 'kharkiv_losk_2_4', site: '', },
	cost 			: { total: 640, price: 640, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_10_28_1300',
	title 			: 'Силикагель наполнитель для котов', 
	hash 			: {},
	manufacturer 	: '', 
	mark 			: '',
	hash 			: { },
	trader 			: { shop: '', site: '', },
	cost 			: { total: 340, price: 340, item: 1, unit: 'шт', },
	note 			: '3.8 кг',
},
{ 
	id  			: '2022_10_28_1001',
	title 			: 'Прокладка дроссельной заслонки', 
	hash 			: { car: 1, },
	manufacturer 	: 'Elring', 
	mark 			: '',
	hash 			: { car: { parts: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', site: '', },
	cost 			: { total: 70, price: 70, item: 1, unit: 'шт', },
	note 			: '',
},
{ 
	id  			: '2022_10_28_1000',
	title 			: 'Спрей карб-клинер', 
	hash 			: { car: 1, },
	manufacturer 	: '', 
	mark 			: '',
	hash 			: { car: { }, },
	trader 			: { shop: 'kharkiv_losk_2_4', site: '', },
	cost 			: { total: 150, price: 150, item: 1, unit: 'шт', },
	note 			: '',
},
{ 
	id  			: '2022_09_05_1000',
	title 			: 'Шини 185/65/R14', 
	hash 			: { car: 1, },
	manufacturer 	: 'Goodyear', 
	mark 			: 'UltraGrip Ice 2',
	hash 			: { car: { parts: 1, }, },
	trader 			: { shop: 'kharkiv_shiny_diski_1', site: 'https://infoshina.com.ua/uk/goodyear-ultragrip-ice-2-185-65-r14-86t', },
	cost 			: { total: 8316, price: 2079, item: 4, unit: 'шт', },
	note 			: '185/65/R14 86 T M+S',
},
{ 
	id  			: '2022_07_28_1803',
	title 			: 'Фільтр салону', 
	hash 			: { car: 1, },
	manufacturer 	: 'Shafer', 
	mark 			: 'SAK44',
	hash 			: { car: { parts: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 0, price: 0, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_07_28_1802',
	title 			: 'Патрубок радіатора грубки', 
	hash 			: { car: 1, },
	manufacturer 	: 'Meyle', 
	mark 			: '1198190014',
	hash 			: { car: { parts: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 0, price: 0, item: 1, unit: 'шт', },
	note 			: 'Короткий с гофрой, выход',
},
{ 
	id  			: '2022_07_28_1801',
	title 			: 'Патрубок радіатора грубки',
	hash 			: { car: 1, },
	manufacturer 	: 'JP Group', 
	mark 			: '1114304300',
	hash 			: { car: { parts: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 0, price: 0, item: 1, unit: 'шт', },
	note 			: 'Длинный, вход',
},
{ 
	id  			: '2022_07_28_1800',
	title 			: 'Радіатор грубки', 
	hash 			: { car: 1, },
	manufacturer 	: 'Febi', 
	mark 			: '',
	hash 			: { car: { parts: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 580, price: 600, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_29_0901',
	title 			: 'Коронка під шуроповерт', 
	hash 			: {},
	manufacturer 	: '32 мм', 
	mark 			: '',
	hash 			: { tool: 1, },
	trader 			: { shop: 'kharkiv_tc_barabashovo', },
	cost 			: { total: 0, price: 0, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_29_0900',
	title 			: 'Бак пластиковий', 
	hash 			: {},
	manufacturer 	: 'Europlast', 
	mark 			: '300 л',
	hash 			: { home: { water: 1, }, },
	trader 			: { shop: 'kharkiv_tc_barabashovo', },
	cost 			: { total: 2800, price: 2800, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_05_0904',
	title 			: 'П\'ятерник', 
	hash 			: {},
	manufacturer 	: '', 
	mark 			: '',
	hash 			: { home: { water: 1, }, },
	trader 			: { shop: 'kharkiv_aquaera_1', },
},
{ 
	id  			: '2022_06_05_0903',
	title 			: 'Манометр', 
	hash 			: {},
	manufacturer 	: '', 
	mark 			: '',
	hash 			: { home: { water: 1, }, },
	trader 			: { shop: 'kharkiv_aquaera_1', },
},
{ 
	id  			: '2022_06_05_0902',
	title 			: 'Реле тиску', 
	hash 			: {},
	manufacturer 	: 'Italtechnica', 
	mark 			: 'PM/5G',
	hash 			: { home: { water: 1, }, },
	trader 			: { shop: 'kharkiv_aquaera_1', },
},
{ 
	id  			: '2022_06_05_0901',
	title 			: 'Гідроакумулятор', 
	hash 			: {},
	manufacturer 	: 'Euroaqua', 
	mark 			: '100 л',
	hash 			: { home: { water: 1, }, },
	trader 			: { shop: 'kharkiv_aquaera_1', },
	cost 			: { total: 6280, price: 6280, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_05_0900',
	title 			: 'Насос', 
	hash 			: {},
	manufacturer 	: 'Euroaqua JET 100', 
	mark 			: '25117002-01',
	hash 			: { home: { water: 1, }, },
	trader 			: { shop: 'kharkiv_aquaera_1', },
	cost 			: { total: 3200, price: 3200, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_1112',
	title 			: 'Фільтр паливний', 
	hash 			: { car: 1, },
	manufacturer 	: 'Febi', 
	mark 			: '24073 8976',
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 220, price: 220, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_1111', 
	title 			: 'Свічки запалювання', 
	hash 			: { car: 1, },
	manufacturer 	: 'Denso', 
	mark 			: 'W20EPBR-S',
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 600, price: 150, item: 4, unit: 'шт', },
	note 			: 'Свечи зажигания трехлепестковые',
},
{ 
	id  			: '2022_06_09_1110',
	title 			: 'Олія трансмісійна', 
	hash 			: { car: 1, },
	manufacturer 	: 'Febi', 
	mark 			: '75W GL-4',
	hash 			: { car: { liquid: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 760, price: 380, item: 2, unit: 'л', },
},
{ 
	id  			: '2022_06_09_1109',
	title 			: 'Вода дистильована', 
	hash 			: { car: 1, },
	manufacturer 	: '', 
	mark 			: '',
	hash 			: { car: { liquid: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 50, price: 10, item: 5, unit: 'л', },
},
{ 
	id  			: '2022_06_09_1108',
	title 			: 'Антифриз',
	hash 			: { car: 1, },
	manufacturer 	: 'Hepu', 
	mark 			: 'P999-G12-005',
	country 		: 'deu',
	hash 			: { car: { liquid: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 750, price: 130, item: 5, unit: 'л', },
},
{ 
	id  			: '2022_06_09_1107',
	title 			: 'Патрубок картерних газів', 
	hash 			: { car: 1, },
	manufacturer 	: 'Topran', 
	mark 			: '109614 3800J49',
	vag 			: '037103211',
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 400, price: 400, item: 1, unit: 'шт', },
	note 			: 'Патрубок пластиковый Г-образный от клапана картерных газов',
},
{ 
	id  			: '2022_06_09_1106', 
	title 			: 'Фланець антифризу', 
	hash 			: { car: 1, },
	manufacturer 	: 'Febi', 
	mark 			: '12410 8624 PA66-GF30',
	vag 			: '037121145',
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 140, price: 140, item: 1, unit: 'шт', },
	note 			: 'На ГБЦ сбоку',
},
{ 
	id  			: '2022_06_09_1105', 
	title 			: 'Помпа', 
	hash 			: { car: 1, },
	manufacturer 	: 'INA', 
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 1000, price: 1000, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_1104', 
	title 			: 'Ролик', 
	hash 			: { car: 1, },
	manufacturer 	: 'INA', 
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 650, price: 650, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_1103', 
	title 			: 'Ролик ГРМ', 
	hash 			: { car: 1, },
	manufacturer 	: 'INA', 
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 500, price: 500, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_1102', 
	title 			: 'Ремінь клиновий', 
	hash 			: { car: 1, },
	manufacturer 	: 'Gates', 
	mark 			: '6389 MC',
	country 		: 'esp',
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 180, price: 180, item: 1, unit: 'шт', },
	note 			: 'Сначала был куплен INA с неровными зубьями за 260 грн, потом обменен на этот с ровными зубьями и дешевле гривен на 80',
},
{ 
	id  			: '2022_06_09_1101', 
	title 			: 'Ремінь полікліновий', 
	hash 			: { car: 1, },
	manufacturer 	: 'Contitech', 
	mark 			: '6 PK 1153',
	country 		: 'rou',
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 420, price: 420, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_1100', 
	title 			: 'Ремінь ГРМ', 
	hash 			: { car: 1, },
	manufacturer 	: 'Contitech', 
	mark 			: 'CT 630. 0433 10022022',
	country 		: 'deu',
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 530, price: 530, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_0831', 
	title 			: 'Резина листова. Рулончик', 
	hash 			: {},
	trader 			: { shop: 'kharkiv_blagbaz', },
	cost 			: { total: 35, price: 35, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_09_0830', 
	title 			: 'Диск відрізний 32х300', 
	hash 			: {},
	hash 			: { tool: { }, },
	trader 			: { shop: 'kharkiv_blagbaz', },
	cost 			: { total: 160, price: 80, item: 2, unit: 'шт', },
},
{ 
	id  			: '2022_06_07_1200', 
	title 			: 'Зарядний пристрій', 
	hash 			: { car: 1, },
	manufacturer 	: 'Dnipro-M', 
	mark 			: 'BC-16',
	site 			: 'https://dnipro-m.ua/tovar/zaryadnoe-ystroistvo-cb-16s/?tab=description',
	hash 			: { car: { }, },
	trader 			: { shop: 'merefa_dnipro_m', },
	cost 			: { total: 1800, price: 1800, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_06_07_1100', 
	title 			: 'Змішувач в ванну (без гусака, тільки душ)', 
	hash 			: {},
	manufacturer 	: 'Haiba', 
	trader 			: { shop: 'merefa_rynok_santehnika_1', },
	cost 			: { total: 1100, price: 1100, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_20_1001', 
	title 			: 'Підсумок для 3 магазинів АК', 
	hash 			: {},
	trader 			: { shop: 'kharkiv_armeysky_1', },
	cost 			: { total: 400, price: 400, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_20_1000', 
	title 			: 'Балаклава', 
	hash 			: {},
	trader 			: { shop: 'kharkiv_gvardeysky_1', },
	cost 			: { total: 120, price: 120, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_20_0900', 
	title 			: 'Телефон', 
	hash 			: {},
	manufacturer 	: 'Xiaomi', 
	mark 			: 'Poco M3 Pro 5G 4/64GB',
	site 			: 'https://elmir.ua/cell_phones/mobile_phone_xiaomi_poco_m3_pro_5g_4_64gb_black_eu.html',
	trader 			: { shop: 'kharkiv_elmir_2', },
	cost 			: { total: 7502, price: 7502, item: 1, unit: 'шт', },
	note 			: 'Для Вови',
},
{ 
	id  			: '2022_05_17_1004', 
	title 			: 'Щітка по металу для болгарки', 
	hash 			: {},
	site 			: 'https://dnipro-m.ua/tovar/shhetka-po-metallu-dnipro-m-konusnaya-gofr-provoloka-125mm/',
	trader 			: { shop: 'merefa_dnipro_m', },
	cost 			: { total: 80, price: 80, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_17_1003', 
	title 			: 'Свердла (набір)', 
	hash 			: {},
	site 			: 'https://dnipro-m.ua/tovar/tovar-nabor-sverl-po-metalu/',
	trader 			: { shop: 'merefa_dnipro_m', },
	cost 			: { total: 230, price: 230, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_17_1002', 
	title 			: 'Диски для болгарки, 1 мм', 
	hash 			: {},
	trader 			: { shop: 'merefa_dnipro_m', },
	cost 			: { total: 210, price: 21, item: 10, unit: 'шт', },
},
{ 
	id  			: '2022_05_17_1001', 
	title 			: 'Шуруповерт', 
	hash 			: {},
	manufacturer 	: 'Dnipro-M', 
	mark 			: 'TD-32Q',
	site 			: 'https://dnipro-m.ua/tovar/drel-shurupovert-setevaya-td-32q/?tab=characteristics',
	trader 			: { shop: 'merefa_dnipro_m', },
	cost 			: { total: 1197, price: 1197, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_17_1000', 
	title 			: 'Болгарка', 
	hash 			: {},
	manufacturer 	: 'Dnipro-M', 
	trader 			: { shop: 'merefa_dnipro_m', },
	cost 			: { total: 1700, price: 1700, item: 1, unit: 'шт', },
	note 			: '960 Вт. Нет на сайте',
},
{ 
	id  			: '2022_05_16_1001', 
	title 			: 'Каністра пластикова для бензину', 
	hash 			: { car: 1, },
	mark 			: '20 л',
	trader 			: { shop: 'kharkiv_avtograd', },
	cost 			: { total: 600, price: 600, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_16_1000', 
	title 			: 'Лійка пластикова для бензину', 
	hash 			: { car: 1, },
	trader 			: { shop: 'kharkiv_avtograd', },
	cost 			: { total: 100, price: 100, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_05_15_2200', 
	title 			: 'Power Bank', 
	hash 			: {},
	manufacturer 	: 'No Name', 
	mark 			: '10000 mAh',
	trader 			: { other: 'Павлюченко И.', },
	cost 			: { total: 400, price: 400, item: 1, unit: 'шт', },
},
{
	id 				: '2022_05_04_1105',
	title 			: 'Ручка дверей',
	hash 			: { car: 1, },
	manufacturer 	: 'Topran',
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 320, price: 320, item: 1, unit: 'шт', },
	note 			: 'Задняя правая',
},
{
	id 				: '2022_05_04_1104',
	title 			: 'Ручка дверей',
	hash 			: { car: 1, },
	manufacturer 	: 'Topran',
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 320, price: 320, item: 1, unit: 'шт', },
	note 			: 'Задняя левая',
},
{
	id 				: '2022_05_04_1103',
	title 			: 'Ручка дверей',
	hash 			: { car: 1, },
	manufacturer 	: 'Topran',
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 500, price: 500, item: 1, unit: 'шт', },
	note 			: 'Водительская с замком-личинкой и проводом. Провод не нужен',
},
{
	id 				: '2022_05_04_1102',
	title 			: 'Рігеля',
	hash 			: { car: 1, },
	manufacturer 	: 'Febi',
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 160, price: 40, item: 4, unit: 'шт', },
	note 			: 'Упоры замков дверей. Шайбы тонкие, гнутся',
},
{
	id 				: '2022_05_04_1101',
	title 			: 'Кліпси дверних ручек',
	hash 			: { car: 1, },
	manufacturer 	: 'VAG',
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 200, price: 50, item: 4, unit: 'шт', },
	note 			: 'П-образные белые пластмасски',
},
{
	id 				: '2022_04_22_1003',
	title 			: 'Втулки стабілізатора',
	hash 			: { car: 1, },
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 150, price: 75, item: 2, unit: 'шт', },
	note 			: 'Резинки',
},
{
	id 				: '2022_04_22_1002',
	title 			: 'Гальмівні колодки',
	hash 			: { car: 1, },
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 900, price: 450, item: 2, unit: 'шт', },
	note 			: '2 комплекта = 8 штук, на все колеса',
},
{
	id 				: '2022_04_22_1001',
	title 			: 'Стойки-амортизатори',
	hash 			: { car: 1, },
	manufacturer 	: 'Meyle',
	hash 			: { car: { part: 1, }, },
	trader 			: { shop: 'kharkiv_losk_2_4', seller: '_maxim_artemovka_losk_2_4', },
	cost 			: { total: 3300, price: 1650, item: 2, unit: 'шт', },
	note 			: 'Передні - ліва, права',
},
{ 
	id  			: '2022_04_10_1000',
	title 			: 'Web-камера', 
	hash 			: {},
	manufacturer 	: 'Media-Tech', 
	mark 			: 'LOOK V MT4107',
	hash 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_elmir_2', site: '', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
},
{ 
	id  			: '2022_04_02_1000',
	title 			: 'Машинка для стрижки', 
	hash 			: {},
	manufacturer 	: 'Philips', 
	mark 			: 'HC3510/15',
	hash 			: { home: {}, },
	trader 			: { shop: 'kharkiv_elmir_2', site: '', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
},
{
	id 				: '2021_12_09_1030',
	title 			: 'Компресор для колес',
	hash 			: { car: 1, },
	manufacturer 	: 'Winso',
	trader 			: { shop: 'kharkiv_losk_11_49', },
},
{
	id 				: '2021_12_09_1002',
	title 			: 'Масляний фільтр',
	hash 			: { car: 1, },
	trader 			: { shop: 'kharkiv_losk_9_97', },
},
{
	id 				: '2021_12_09_1001',
	title 			: 'Олія моторна',
	hash 			: { car: 1, },
	manufacturer 	: 'Valvoline MaxLife',
	mark 			: '10w40 Synthetic Technology',
	trader 			: { shop: 'kharkiv_losk_9_97', },
	cost 			: { total: 750, price: 130, item: 5, unit: 'л', },
	note 			: 'Бензин, газ, дизель. Допуск - VW 50200/50500',
},
{
	id 				: '2021_00_00_1206',
	title 			: 'Дроти ВВ (свічні)',
	hash 			: { car: 1, },
	manufacturer 	: 'Beru',
	mark 			: 'ZEF 561',
	country 		: 'fra',
	hash 			: { car: { part: 1, }, },
	trader 			: { seller: '_alexandr_sto_pivdennePushka', },
	note 			: 'Beru 0300.890.561',
},
{
	id 				: '2021_00_000_1205',
	title 			: 'Кришка трамблера',
	hash 			: { car: 1, },
	manufacturer 	: 'Metzger',
},
{
	id 				: '2021_00_00_1204',
	title 			: 'Лямбда-зонд',
	hash 			: { car: 1, },
	manufacturer 	: 'Bosch',
	code 			: '0 258 005 133',
	country 		: 'fra',
	hash 			: { car: { part: 1, }, },
	trader 			: { seller: '_alexandr_sto_pivdennePushka', },
},
{
	id 				: '2021_00_00_1203',
	title 			: 'Патрубок ДМРВ-колектора',
	hash 			: { car: 1, },
	mark 			: 'хобот',
	trader 			: { shop: 'kharkiv_avtograd', },
	cost 			: { total: 500, price: 500, item: 1, unit: 'шт', },
	note 			: 'б/у',
},
{
	id 				: '2021_00_00_1202',
	title 			: 'ДМРВ',
	hash 			: { car: 1, },
	manufacturer 	: 'Bosch',
	trader 			: { shop: 'kharkiv_avtograd', },
	cost 			: { total: 2700, price: 2700, item: 1, unit: 'шт', },
	note 			: 'б/у',
},
{ 
	id  			: '2020_10_15_1000',
	title 			: 'Батарея для безперебійника', 
	hash 			: {},
	manufacturer 	: 'CSB 12В 9Ач', 
	mark 			: 'HR1234WF2',
	hash 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_elmir_2', },
	cost 			: { total: 0, price: 0, item: 2, unit: 'шт', },
},
{ 
	id  			: '2020_08_10_0900',
	title 			: 'Котушка запалювання', 
	hash 			: { car: 1, },
	manufacturer 	: 'Bremi', 
	mark 			: '',
	hash 			: { car: { parts: 1, }, },
	trader 			: { shop: 'kharkiv_losk_insideParts', },
	cost 			: { total: 900, price: 900, item: 1, unit: 'шт', },
},
{ 
	id  			: '2020_04_18_0900',
	title 			: 'Відеореєстратор', 
	hash 			: { car: 1, },
	manufacturer 	: 'Xiaomi Yi Smart', 
	mark 			: 'Dash Camera',
	hash 			: { car: { }, },
	trader 			: { shop: 'kharkiv_elmir_1', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
	note 			: 'Для Citroen C1, на ДР Скирда',
},
{ 
	id  			: '2019_11_19_1000',
	title 			: 'Ваги підлогові', 
	hash 			: {},
	manufacturer 	: 'Mirta', 
	mark 			: 'SB-3120',
	hash 			: { home: {}, },
	trader 			: { shop: 'kharkiv_elmir_1', site: '', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
},
{ 
	id  			: '2018_06_04_1000',
	title 			: 'Ноутбук', 
	hash 			: {},
	manufacturer 	: 'Lenovo', 
	mark 			: 'IdeaPad 320',
	hash 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_comfy_1', site: '', },
	cost 			: { total: 16000, price: 16000, item: 1, unit: 'шт', },
},
{ 
	id  			: '2018_03_12_1000',
	title 			: 'HDD SATA 2 Tb', 
	hash 			: {},
	manufacturer 	: 'Seagate', 
	mark 			: 'Barracuda',
	hash 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_elmir_2', site: '', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
},
{ 
	id  			: '2018_01_23_1000',
	title 			: 'SSD SATA 128 Gb', 
	hash 			: {},
	manufacturer 	: 'Silicon Power', 
	mark 			: 'A55',
	hash 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_elmir_1', site: '', },
	cost 			: { total: 1482, price: 1482, item: 1, unit: 'шт', },
},
{ 
	id  			: '2017_09_29_1000',
	title 			: 'USB Flash 64 Gb', 
	hash 			: {},
	manufacturer 	: 'GoodRam', 
	mark 			: 'UTS3',
	hash 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_elmir_1', site: '', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
},
{ 
	id  			: '2008_06_16_1000',
	title 			: 'UPS Джерело безперебійного живлення', 
	hash 			: {},
	manufacturer 	: 'Mustek', 
	mark 			: 'PowerMust 1400 USB',
	hash 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_elmir_1', site: '', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
},
{ 
	id  			: '2008_03_07_1600',
	title 			: 'Монітор TFT LCD', 
	hash 			: {},
	manufacturer 	: 'LG Flatron', 
	mark 			: 'L204WT',
	hash 			: { pc: {}, },
	trader 			: { shop: 'kharkiv_univermag_kharkiv', site: '', },
	cost 			: { total: 1, price: 1, item: 1, unit: 'шт', },
},
{ 
	id  			: '2007_11_21_1500',
	title 			: 'Сінтезатор', 
	hash 			: {},
	manufacturer 	: 'Casio', 
	mark 			: 'CDP 100',
	hash 			: { studio: {}, },
	trader 			: { shop: 'kharkiv_atlanta_show', site: '', },
	cost 			: { total: 3510, price: 3510, item: 1, unit: 'шт', },
},














];



let objListBuy = {};
arrListBuy.forEach( k => {
	objListBuy[ k.id ] = k;
});





